project_id = "hrbltonpknsxfwdyzykz"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.bootstrap-admin]
    verify_jwt = false
  [functions.delete-account]
    verify_jwt = false
  [functions.moderate-profile]
    verify_jwt = true
