// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-dictionary.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import { DICIONARIO } from "npm:@/data/dicionario";
var search_dictionary_default = defineTool({
  name: "search_dictionary",
  title: "Search Umbundu \u21C4 Portuguese dictionary",
  description: "Search the Kwendi bilingual dictionary. Matches Portuguese or Umbundu terms (case-insensitive substring). Returns up to 25 entries.",
  inputSchema: {
    query: z.string().min(1).describe("Word or fragment to search for, in Portuguese or Umbundu."),
    categoria: z.enum([
      "saudacoes",
      "familia",
      "numeros",
      "tempo",
      "corpo",
      "natureza",
      "cultura",
      "verbos",
      "objetos"
    ]).optional().describe("Optional category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, categoria }) => {
    const q = query.toLowerCase();
    const results = DICIONARIO.filter(
      (e) => (!categoria || e.categoria === categoria) && (e.pt.toLowerCase().includes(q) || e.umbundu.toLowerCase().includes(q))
    ).slice(0, 25);
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { results, count: results.length }
    };
  }
});

// src/lib/mcp/tools/list-stories.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { HISTORIAS } from "npm:@/data/historias";
var list_stories_default = defineTool2({
  name: "list_stories",
  title: "List Kwendi stories",
  description: "List Angolan cultural stories available in Kwendi with their region, era, level, and duration. Optionally filter by level.",
  inputSchema: {
    nivel: z2.enum(["Iniciante", "Interm\xE9dio", "Avan\xE7ado"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ nivel }) => {
    const items = HISTORIAS.filter((h) => !nivel || h.nivel === nivel).map((h) => ({
      id: h.id,
      titulo: h.titulo,
      subtitulo: h.subtitulo,
      regiao: h.regiao,
      epoca: h.epoca,
      nivel: h.nivel,
      duracaoMin: h.duracaoMin
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items, count: items.length }
    };
  }
});

// src/lib/mcp/tools/list-curiosities.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { curiosidades } from "npm:@/data/curiosidades";
var list_curiosities_default = defineTool3({
  name: "list_curiosities",
  title: "List Angolan culture curiosities",
  description: "List cultural curiosities from Kwendi (nature, history, culture, gastronomy, languages, monuments of Angola). Optionally filter by category.",
  inputSchema: {
    categoria: z3.enum(["natureza", "historia", "cultura", "gastronomia", "linguas", "monumentos"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ categoria }) => {
    const items = curiosidades.filter((c) => !categoria || c.categoria === categoria).map((c) => ({
      categoria: c.categoria,
      titulo: c.titulo,
      subtitulo: c.subtitulo,
      resumo: c.resumo
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items, count: items.length }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "kwendi-mcp",
  title: "Kwendi MCP",
  version: "0.1.0",
  instructions: "Tools for Kwendi, an app to learn the Umbundu language and Angolan culture. Use `search_dictionary` for PT \u21C4 Umbundu lookups, `list_stories` for Angolan tales, and `list_curiosities` for cultural facts about Angola.",
  tools: [search_dictionary_default, list_stories_default, list_curiosities_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
